apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-traffic
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vastraco.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow all traffic between workloads in the same namespace
    - from:
        - podSelector: {}
    # Allow ingress from KGateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kgateway-system
